/**
 * Gemini AI Service
 * Handles AI-powered content generation for Instagram posts
 */

export interface AIGeneratedContent {
  backgroundImage: string;
  imageText: string;
  postDescription: string;
  hashtags: string[];
  style: {
    textColor: string;
    textSize: string;
    textPosition: string;
    backgroundColor: string;
  };
}

export interface AICarouselContent {
  slides: AIGeneratedContent[];
  mainDescription: string;
  mainHashtags: string[];
}

export interface AIGenerationRequest {
  userDescription: string;
  referencePosts: string;
  userStyle?: string;
  targetAudience?: string;
  brandGuidelines?: string;
}

export class GeminiService {
  private apiKey: string;
  private baseUrl = "https://generativelanguage.googleapis.com/v1beta";
  private model = "gemini-2.0-flash"; // Using Gemini Flash 1.5 (stable version)

  constructor(apiKey?: string) {
    if (apiKey) {
      this.apiKey = apiKey;
    } else {
      // Only use useRuntimeConfig if no API key is provided and we're in a Nuxt context
      try {
        const config = useRuntimeConfig();
        this.apiKey = config.public.GEMINI_API_KEY || "";
      } catch (error) {
        // Fallback to environment variable if useRuntimeConfig fails
        this.apiKey = process.env.GEMINI_API_KEY || "";
      }
    }

    if (!this.apiKey) {
      console.warn(
        "Gemini API key not found. Please set GEMINI_API_KEY in your environment."
      );
    }
  }

  /**
   * Generate Instagram post content using Gemini AI
   */
  async generatePostContent(
    request: AIGenerationRequest
  ): Promise<AIGeneratedContent> {
    try {
      const prompt = this.buildPrompt(request);

      console.log("Making request to Gemini API with model:", this.model);
      console.log(
        "API Key (first 10 chars):",
        this.apiKey.substring(0, 10) + "..."
      );

      const response = await fetch(
        `${this.baseUrl}/models/${this.model}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: {
              role: "USER",
              parts: {
                text: prompt,
              },
            },
            generation_config: {
              response_modalities: ["TEXT"],
              temperature: 0.7,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 1024,
            },
            //  safetySettings: {
            //   method: "PROBABILITY",
            //   category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            //   threshold: "BLOCK_MEDIUM_AND_ABOVE"
            // }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        console.error("Gemini API error response:", errorData);
        throw new Error(
          `Gemini API error: ${response.status} ${response.statusText} - ${JSON.stringify(errorData)}`
        );
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!generatedText) {
        throw new Error("No content generated by Gemini AI");
      }

      return this.parseAIResponse(generatedText);
    } catch (error) {
      console.error("Error generating content with Gemini:", error);
      throw error;
    }
  }

  /**
   * Generate carousel content for multiple slides
   */
  async generateCarouselContent(
    request: AIGenerationRequest,
    slideCount: number
  ): Promise<AICarouselContent> {
    try {
      const prompt = this.buildCarouselPrompt(request, slideCount);

      console.log(
        "Making carousel request to Gemini API with model:",
        this.model
      );

      const response = await fetch(
        `${this.baseUrl}/models/${this.model}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: {
              role: "USER",
              parts: {
                text: prompt,
              },
            },
            generation_config: {
              response_modalities: ["TEXT"],
              temperature: 0.7,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 2048, // Increased for multiple slides
            },
            // safetySettings: {
            //   method: "PROBABILITY",
            //   category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            //   threshold: "BLOCK_MEDIUM_AND_ABOVE"
            // }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        console.error("Gemini API error response:", errorData);
        throw new Error(
          `Gemini API error: ${response.status} ${response.statusText} - ${JSON.stringify(errorData)}`
        );
      }

      const data = await response.json();
      const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!generatedText) {
        throw new Error("No content generated by Gemini AI");
      }

      return this.parseCarouselResponse(generatedText);
    } catch (error) {
      console.error("Error generating carousel content with Gemini:", error);
      throw error;
    }
  }

  /**
   * Build the prompt for Gemini AI
   */
  private buildPrompt(request: AIGenerationRequest): string {
    return `
Você é um especialista em criação de conteúdo para Instagram e design. Sua tarefa é criar conteúdo envolvente para posts do Instagram baseado na solicitação do usuário e nos posts de referência.

SOLICITAÇÃO DO USUÁRIO:
"${request.userDescription}"

ANÁLISE DOS POSTS DE REFERÊNCIA:
${request.referencePosts}

INSTRUÇÕES:
1. Analise os posts de referência para entender o estilo, tom e padrões de conteúdo
2. Crie conteúdo que corresponda à solicitação do usuário mantendo consistência com o estilo de referência
3. Gere uma legenda para cada imagem da postagem que seria atrativo e causaria engajamento no Instagram
4. Crie texto sobreposto que seja atrativo e envolvente
5. Escreva uma descrição de post convincente com hashtags relevantes

Por favor, responda APENAS no seguinte formato de texto simples (sem JSON, sem markdown, use apenas \n to end the line text):

DESCRIÇÃO_IMAGEM: [Descrição detalhada da imagem de fundo para gerar]\n
TEXTO_IMAGEM: [Texto para sobrepor na imagem - baseado no contexto pode ser curto ou longo]\n
DESCRIÇÃO_POST: [Descrição envolvente do post com chamada cativante, busque se basear em posts virais]\n
HASHTAGS: [hashtag1,hashtag2,hashtag3,hashtag4,hashtag5]\n
COR_TEXTO: #FFFFFF\n
TAMANHO_TEXTO: large\n
POSIÇÃO_TEXTO: center\n

IMPORTANTE:
- Mantenha o imageText o mais impactante e engajativo possível
- Torne a postDescription envolvente e autêntica
- Inclua 5-10 hashtags relevantes
- Certifique-se de que a descrição da imagem de fundo seja bem detalhada, busque criar a imagem mais cativante para o cenário informado
- Combine com o tom e estilo dos posts de referência
- Certifique-se de que o conteúdo esteja alinhado com a solicitação específica do usuário
- TODO O CONTEÚDO DEVE SER EM PORTUGUÊS BRASILEIRO
- Use linguagem natural e envolvente típica do Instagram brasileiro
- Inclua hashtags populares no Brasil quando relevante

Gere o conteúdo agora:`;
  }

  /**
   * Build the prompt for carousel content generation
   */
  private buildCarouselPrompt(
    request: AIGenerationRequest,
    slideCount: number
  ): string {
    return `
Você é um especialista em criação de conteúdo para Instagram e design. Sua tarefa é criar conteúdo envolvente para um CARROSSEL de ${slideCount} slides do Instagram baseado na solicitação do usuário e nos posts de referência.

SOLICITAÇÃO DO USUÁRIO:
"${request.userDescription}"

ANÁLISE DOS POSTS DE REFERÊNCIA:
${request.referencePosts}

INSTRUÇÕES:
1. Analise os posts de referência para entender o estilo, tom e padrões de conteúdo
2. PRIMEIRO: Planeje uma estratégia de "thread" onde cada slide complementa os outros
3. Cada slide deve adicionar nova informação específica ou continuar a narrativa
4. Crie uma descrição principal do post que funcione para todo o carrossel
5. Inclua hashtags relevantes para todo o carrossel

ETAPA 1 - PLANEJAMENTO:
Defina o conceito geral e como cada slide se encaixa na sequência.

ETAPA 2 - EXECUÇÃO:
Crie cada slide seguindo o planejamento.

Por favor, responda APENAS no seguinte formato de texto simples (sem JSON, sem markdown, sem explicações, use apenas \n to end the line text):

ESTRATÉGIA_THREAD: [Explique como os ${slideCount} slides se complementam e a progressão da informação]\n

VOCÊ DEVE CRIAR EXATAMENTE ${slideCount} SLIDES. Formato para cada slide:

SLIDE_1_CONCEITO: [Função específica deste slide na sequência - ex: introdução, problema, etc.]\n
DESCRIÇÃO_IMAGEM: [Descrição detalhada da imagem baseada no conceito planejado]\n
TEXTO_IMAGEM: [Texto para sobrepor na imagem]\n
DESCRIÇÃO_SLIDE: [Descrição específica do slide]\n
HASHTAGS_SLIDE: [hashtag1,hashtag2]\n
//***///##//
SLIDE_2_CONCEITO: [Função específica deste slide na sequência - ex: desenvolvimento, solução, etc.]\n
DESCRIÇÃO_IMAGEM: [Descrição detalhada da imagem baseada no conceito planejado]\n
TEXTO_IMAGEM: [Texto para sobrepor na imagem]\n
DESCRIÇÃO_SLIDE: [Descrição específica do slide]\n
HASHTAGS_SLIDE: [hashtag3,hashtag4]\n
//***///##//
SLIDE_3_CONCEITO: [Função específica deste slide na sequência - ex: conclusão, call-to-action, etc.]\n
DESCRIÇÃO_IMAGEM: [Descrição detalhada da imagem baseada no conceito planejado]\n
TEXTO_IMAGEM: [Texto para sobrepor na imagem]\n
DESCRIÇÃO_SLIDE: [Descrição específica do slide]\n
HASHTAGS_SLIDE: [hashtag5,hashtag6]\n
//***///##//

DESCRIÇÃO_PRINCIPAL: [Descrição principal do carrossel - chamada cativante e envolvente, busque se basear em posts virais]\n
HASHTAGS_PRINCIPAIS: [hashtag1,hashtag2,hashtag3,hashtag4,hashtag5]\n

IMPORTANTE:
- Crie exatamente ${slideCount} slides
- Cada slide deve ter conteúdo único mas relacionado
- Os slides devem contar uma história ou sequência lógica
- Mantenha consistência visual entre os slides
- TODO O CONTEÚDO DEVE SER EM PORTUGUÊS BRASILEIRO
- Use linguagem natural e envolvente típica do Instagram brasileiro
- Inclua hashtags populares no Brasil quando relevante

Gere o conteúdo do carrossel agora:`;
  }

  /**
   * Parse AI response and extract structured data
   */
  private parseAIResponse(response: string): AIGeneratedContent {
    try {
      // Parse the response using the new format with \n line endings
      const lines = response
        .split("\n")
        .filter((line) => line.trim().length > 0);

      let backgroundImage = "";
      let imageText = "";
      let postDescription = "";
      let hashtagsText = "";
      let textColor = "#FFFFFF";
      let textSize = "large";
      let textPosition = "center";

      for (const line of lines) {
        const trimmedLine = line.trim();

        if (trimmedLine.startsWith("DESCRIÇÃO_IMAGEM:")) {
          backgroundImage = trimmedLine.replace("DESCRIÇÃO_IMAGEM:", "").trim();
        } else if (trimmedLine.startsWith("TEXTO_IMAGEM:")) {
          imageText = trimmedLine.replace("TEXTO_IMAGEM:", "").trim();
        } else if (trimmedLine.startsWith("DESCRIÇÃO_POST:")) {
          postDescription = trimmedLine.replace("DESCRIÇÃO_POST:", "").trim();
        } else if (trimmedLine.startsWith("HASHTAGS:")) {
          hashtagsText = trimmedLine.replace("HASHTAGS:", "").trim();
        } else if (trimmedLine.startsWith("COR_TEXTO:")) {
          textColor = trimmedLine.replace("COR_TEXTO:", "").trim();
        } else if (trimmedLine.startsWith("TAMANHO_TEXTO:")) {
          textSize = trimmedLine.replace("TAMANHO_TEXTO:", "").trim();
        } else if (trimmedLine.startsWith("POSIÇÃO_TEXTO:")) {
          textPosition = trimmedLine.replace("POSIÇÃO_TEXTO:", "").trim();
        }
        // Removed COR_FUNDO parsing - no longer using background colors
      }

      // Parse hashtags
      const hashtags = hashtagsText
        .split(",")
        .map((tag) => tag.trim())
        .filter((tag) => tag.length > 0);

      return {
        backgroundImage:
          backgroundImage || "Modern Instagram-worthy background",
        imageText: imageText || "Generated Content",
        postDescription: postDescription || "Generated description",
        hashtags: hashtags.length > 0 ? hashtags : ["instagram", "post", "ai"],
        style: {
          textColor: textColor || "#FFFFFF",
          textSize: textSize || "large",
          textPosition: textPosition || "center",
          backgroundColor: "transparent", // Always transparent - no background colors
        },
      };
    } catch (error) {
      console.error("Error parsing AI response:", error);

      // Fallback: try to extract content manually
      return this.fallbackParsing(response);
    }
  }

  /**
   * Parse carousel AI response and extract structured data
   */
  private parseCarouselResponse(response: string): AICarouselContent {
    try {
      console.log("Raw carousel response:", response);

      // Extract strategy first
      let threadStrategy = "";
      const strategyMatch = response.match(
        /ESTRATÉGIA_THREAD:\s*(.+?)(?=\n|$)/
      );
      if (strategyMatch) {
        threadStrategy = strategyMatch[1].trim();
        console.log("Thread strategy:", threadStrategy);
      }

      // Parse the response using the new format with //***///##// separating slides
      const slideSections = response.split("//***///##//");

      console.log("Split into sections:", slideSections.length);

      const slides: AIGeneratedContent[] = [];
      let mainDescription = "";
      let mainHashtags: string[] = [];

      // Parse each slide section
      for (let i = 0; i < slideSections.length; i++) {
        const section = slideSections[i];
        console.log(`Processing section ${i + 1}:`, section);

        const lines = section
          .split("\n")
          .filter((line) => line.trim().length > 0);

        let slideConcepto = "";
        let backgroundImage = "";
        let imageText = "";
        let postDescription = "";
        let hashtagsText = "";
        let isMainSection = false;

        for (const line of lines) {
          const trimmedLine = line.trim();

          if (
            trimmedLine.startsWith("SLIDE_") &&
            trimmedLine.includes("_CONCEITO:")
          ) {
            slideConcepto = trimmedLine
              .replace(/SLIDE_\d+_CONCEITO:/, "")
              .trim();
          } else if (trimmedLine.startsWith("DESCRIÇÃO_IMAGEM:")) {
            backgroundImage = trimmedLine
              .replace("DESCRIÇÃO_IMAGEM:", "")
              .trim();
          } else if (trimmedLine.startsWith("TEXTO_IMAGEM:")) {
            imageText = trimmedLine.replace("TEXTO_IMAGEM:", "").trim();
          } else if (trimmedLine.startsWith("DESCRIÇÃO_SLIDE:")) {
            postDescription = trimmedLine
              .replace("DESCRIÇÃO_SLIDE:", "")
              .trim();
          } else if (trimmedLine.startsWith("HASHTAGS_SLIDE:")) {
            hashtagsText = trimmedLine.replace("HASHTAGS_SLIDE:", "").trim();
          } else if (trimmedLine.startsWith("DESCRIÇÃO_PRINCIPAL:")) {
            mainDescription = trimmedLine
              .replace("DESCRIÇÃO_PRINCIPAL:", "")
              .trim();
            isMainSection = true;
          } else if (trimmedLine.startsWith("HASHTAGS_PRINCIPAIS:")) {
            const mainHashtagsText = trimmedLine
              .replace("HASHTAGS_PRINCIPAIS:", "")
              .trim();
            mainHashtags = mainHashtagsText
              .split(",")
              .map((tag) => tag.trim())
              .filter((tag) => tag.length > 0);
            isMainSection = true;
          }
        }

        console.log(`Section ${i + 1} parsed:`, {
          slideConcepto,
          backgroundImage,
          imageText,
          postDescription,
          hashtagsText,
          isMainSection,
        });

        // If this section has slide content (not main section), add it as a slide
        // More lenient check - just need backgroundImage OR imageText
        if (!isMainSection && (backgroundImage || imageText)) {
          const hashtags = hashtagsText
            .split(",")
            .map((tag) => tag.trim())
            .filter((tag) => tag.length > 0);

          // Enhance background image description with the slide concept
          const enhancedBackgroundImage = backgroundImage;
          slides.push({
            backgroundImage: enhancedBackgroundImage,
            imageText: imageText || "Generated Content",
            postDescription: postDescription || "Generated description",
            hashtags: hashtags.length > 0 ? hashtags : ["instagram", "post"],
            style: {
              textColor: "#FFFFFF",
              textSize: "large",
              textPosition: "center",
              backgroundColor: "transparent",
            },
          });

          console.log(
            `Added slide ${slides.length} with concept "${slideConcepto}":`,
            slides[slides.length - 1]
          );
        } else if (!isMainSection) {
          console.log(`Section ${i + 1} skipped - missing content:`, {
            slideConcepto,
            backgroundImage,
            imageText,
            isMainSection,
          });
        }
      }

      console.log("Total slides parsed:", slides.length);

      return {
        slides:
          slides.length > 0
            ? slides
            : [
                {
                  backgroundImage: "Modern Instagram-worthy background",
                  imageText: "Generated Content",
                  postDescription: "Generated description",
                  hashtags: ["instagram", "post", "ai"],
                  style: {
                    textColor: "#FFFFFF",
                    textSize: "large",
                    textPosition: "center",
                    backgroundColor: "transparent",
                  },
                },
              ],
        mainDescription: mainDescription || "Generated carousel post",
        mainHashtags:
          mainHashtags.length > 0
            ? mainHashtags
            : ["instagram", "carousel", "ai"],
      };
    } catch (error) {
      console.error("Error parsing carousel AI response:", error);

      // Fallback: create single slide
      return this.fallbackCarouselParsing(response);
    }
  }

  /**
   * Fallback parsing for carousel if JSON parsing fails
   */
  private fallbackCarouselParsing(response: string): AICarouselContent {
    return {
      slides: [
        {
          backgroundImage:
            "Modern Instagram-worthy background with soft lighting and aesthetic appeal",
          imageText: "Generated Content",
          postDescription: response.substring(0, 200) + "...",
          hashtags: ["#instagram", "#content", "#ai"],
          style: {
            textColor: "#FFFFFF",
            textSize: "large",
            textPosition: "center",
            backgroundColor: "transparent",
          },
        },
      ],
      mainDescription: response.substring(0, 200) + "...",
      mainHashtags: ["#instagram", "#content", "#ai"],
    };
  }

  /**
   * Fallback parsing if JSON parsing fails
   */
  private fallbackParsing(response: string): AIGeneratedContent {
    return {
      backgroundImage:
        "Modern Instagram-worthy background with soft lighting and aesthetic appeal",
      imageText: "Generated Content",
      postDescription: response.substring(0, 200) + "...",
      hashtags: ["#instagram", "#content", "#ai"],
      style: {
        textColor: "#FFFFFF",
        textSize: "large",
        textPosition: "center",
        backgroundColor: "transparent",
      },
    };
  }

  /**
   * Generate background image using Gemini AI image generation
   */
  async generateBackgroundImage(description: string): Promise<string> {
    try {
      console.log(
        "Generating image with Gemini 2.0 Flash Exp for:",
        description
      );

      const imageModel = "gemini-2.0-flash-exp"; // Specific model for image generation

      const response = await fetch(
        `${this.baseUrl}/models/${imageModel}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: {
              role: "USER",
              parts: {
                text: `Gere uma imagem para Instagram com a seguinte descrição: ${description}.
                       A imagem deve ser profissional, atrativa e pensada para ser vista em um celular em redes sociais brasileiras.
                       Formato: 1080x1350 pixels (formato Instagram).`,
              },
            },
            generation_config: {
              response_modalities: ["TEXT", "IMAGE"],
              // response_modalities: ["IMAGE"],
              temperature: 0.8,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 512,
            },
            // safetySettings: {
            // method: "PROBABILITY",
            // category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            // threshold: "BLOCK_MEDIUM_AND_ABOVE"
            // }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        console.error("Gemini image generation error:", errorData);
        throw new Error(`Gemini image generation failed: ${response.status}`);
      }

      const data = await response.json();
      console.log("Gemini image response:", data);

      // Check if there's an image in the response
      const candidate = data.candidates?.[0];
      if (candidate?.content?.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData?.mimeType?.startsWith("image/")) {
            // Convert base64 to data URL
            const imageData = part.inlineData.data;
            const mimeType = part.inlineData.mimeType;
            return `data:${mimeType};base64,${imageData}`;
          }
        }
      }

      // If no image found, fallback to Unsplash
      console.log("No image generated by Gemini, using fallback");
      const keywords = description.split(" ").slice(0, 3).join(",");
      return `https://source.unsplash.com/1080x1350/?${encodeURIComponent(keywords)}`;
    } catch (error) {
      console.error("Error generating background image:", error);
      // Fallback to Unsplash
      const keywords = description.split(" ").slice(0, 3).join(",");
      return `https://source.unsplash.com/1080x1350/?${encodeURIComponent(keywords)}`;
    }
  }

  /**
   * Convert image to base64 format
   */
  private async convertImageToBase64(
    imageUrl: string
  ): Promise<{ base64: string; mimeType: string }> {
    try {
      if (imageUrl.startsWith("data:")) {
        // Already a data URL, extract base64 and mime type
        const [header, data] = imageUrl.split(",");
        const mimeType = header.split(":")[1].split(";")[0];
        return { base64: data, mimeType };
      }

      // Fetch the image and convert to base64
      const response = await fetch(imageUrl);
      if (!response.ok) {
        throw new Error(`Failed to fetch image: ${response.status}`);
      }

      const blob = await response.blob();
      const mimeType = blob.type || "image/jpeg";

      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => {
          const result = reader.result as string;
          const base64 = result.split(",")[1]; // Remove data URL prefix
          resolve({ base64, mimeType });
        };
        reader.onerror = () =>
          reject(new Error("Failed to convert image to base64"));
        reader.readAsDataURL(blob);
      });
    } catch (error) {
      console.error("Error converting image to base64:", error);
      throw error;
    }
  }

  /**
   * Edit an existing image using Gemini AI
   */
  async editImage(imageData: string, editPrompt: string): Promise<string> {
    try {
      console.log("Editing image with Gemini 2.0 Flash Exp:", editPrompt);

      const imageModel = "gemini-2.0-flash-exp";

      // Convert image to proper base64 format
      const { base64, mimeType } = await this.convertImageToBase64(imageData);

      console.log("Image converted to base64, mime type:", mimeType);

      const response = await fetch(
        `${this.baseUrl}/models/${imageModel}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: {
              role: "USER",
              parts: [
                {
                  inlineData: {
                    mimeType: mimeType,
                    data: base64,
                  },
                },
                {
                  text: `${editPrompt}. Mantenha o formato 1080x1350 pixels adequado para Instagram.`,
                },
              ],
            },
            generation_config: {
              response_modalities: ["TEXT", "IMAGE"],
              temperature: 0.8,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 512,
            },
            // safetySettings: {
            //   method: "PROBABILITY",
            //   category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            //   threshold: "BLOCK_MEDIUM_AND_ABOVE"
            // }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        console.error("Gemini image editing error:", errorData);
        throw new Error(`Gemini image editing failed: ${response.status}`);
      }

      const data = await response.json();
      console.log("Gemini image edit response:", data);

      // Check if there's an edited image in the response
      const candidate = data.candidates?.[0];
      if (candidate?.content?.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData?.mimeType?.startsWith("image/")) {
            const editedImageData = part.inlineData.data;
            const editedMimeType = part.inlineData.mimeType;
            return `data:${editedMimeType};base64,${editedImageData}`;
          }
        }
      }

      // If no edited image found, return original
      console.log("No edited image generated by Gemini, returning original");
      return imageData;
    } catch (error) {
      console.error("Error editing image:", error);
      // Return original image on error
      return imageData;
    }
  }

  /**
   * Validate API key
   */
  isConfigured(): boolean {
    return !!this.apiKey;
  }

  /**
   * Test the Gemini API connection
   */
  async testConnection(): Promise<boolean> {
    try {
      const response = await fetch(
        `${this.baseUrl}/models/${this.model}:generateContent?key=${this.apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: "Hello, this is a test message.",
                  },
                ],
              },
            ],
          }),
        }
      );

      return response.ok;
    } catch (error) {
      console.error("Gemini API connection test failed:", error);
      return false;
    }
  }
}

/**
 * AI Content Generator
 * High-level service that combines Instagram data with AI generation
 */
export class AIContentGenerator {
  private geminiService: GeminiService;
  private instagramPostsFetcher: any;

  constructor() {
    this.geminiService = new GeminiService();
    // Import will be resolved at runtime
    this.instagramPostsFetcher = null;
  }

  /**
   * Initialize the service with Instagram posts fetcher
   */
  async initialize() {
    const { instagramPostsFetcher } = await import("./instagram");
    this.instagramPostsFetcher = instagramPostsFetcher;
  }

  /**
   * Generate complete post content with AI
   */
  async generatePost(
    userDescription: string,
    userId: string
  ): Promise<AIGeneratedContent & { backgroundImageUrl: string }> {
    try {
      // Initialize if needed
      if (!this.instagramPostsFetcher) {
        await this.initialize();
      }

      // Get reference posts
      const referencePosts =
        await this.instagramPostsFetcher.getPostsSummaryForAI(userId);

      // Generate content with AI
      const aiContent = await this.geminiService.generatePostContent({
        userDescription,
        referencePosts,
      });

      // Generate background image
      const backgroundImageUrl =
        await this.geminiService.generateBackgroundImage(
          aiContent.backgroundImage
        );

      return {
        ...aiContent,
        backgroundImageUrl,
      };
    } catch (error) {
      console.error("Error generating post:", error);
      throw error;
    }
  }

  /**
   * Generate carousel content with AI
   */
  async generateCarousel(
    userDescription: string,
    userId: string,
    slideCount: number
  ): Promise<AICarouselContent> {
    try {
      // Initialize if needed
      if (!this.instagramPostsFetcher) {
        await this.initialize();
      }

      // Get reference posts
      const referencePosts =
        await this.instagramPostsFetcher.getPostsSummaryForAI(userId);

      // Generate carousel content with AI
      const carouselContent = await this.geminiService.generateCarouselContent(
        {
          userDescription,
          referencePosts,
        },
        slideCount
      );

      return carouselContent;
    } catch (error) {
      console.error("Error generating carousel:", error);
      throw error;
    }
  }

  /**
   * Generate background images for slides
   */
  async generateSlideImages(slides: AIGeneratedContent[]): Promise<string[]> {
    try {
      const imagePromises = slides.map((slide, index) => {
        // The slide.backgroundImage already contains the concept information
        // from the parsing, so we can use it directly for better context
        console.log(
          `Generating image ${index + 1} with description:`,
          slide.backgroundImage
        );

        return this.geminiService.generateBackgroundImage(
          slide.backgroundImage
        );
      });

      return await Promise.all(imagePromises);
    } catch (error) {
      console.error("Error generating slide images:", error);
      throw error;
    }
  }

  /**
   * Generate single background image
   */
  async generateBackgroundImage(description: string): Promise<string> {
    return await this.geminiService.generateBackgroundImage(description);
  }

  /**
   * Edit an existing image
   */
  async editImage(imageData: string, editPrompt: string): Promise<string> {
    return await this.geminiService.editImage(imageData, editPrompt);
  }

  /**
   * Check if the service is properly configured
   */
  isReady(): boolean {
    return this.geminiService.isConfigured();
  }
}

// Export factory functions to avoid calling useRuntimeConfig at module level
let _geminiService: GeminiService | null = null;
let _aiContentGenerator: AIContentGenerator | null = null;

export function getGeminiService(): GeminiService {
  if (!_geminiService) {
    _geminiService = new GeminiService();
  }
  return _geminiService;
}

export function getAIContentGenerator(): AIContentGenerator {
  if (!_aiContentGenerator) {
    _aiContentGenerator = new AIContentGenerator();
  }
  return _aiContentGenerator;
}

// Legacy exports for backward compatibility
export const geminiService = {
  get instance() {
    return getGeminiService();
  },
};

export const aiContentGenerator = {
  get instance() {
    return getAIContentGenerator();
  },
};
